runtime! debian.vim

filetype plugin indent on " identificar o tipo de arquivo

syntax on " habilita destaque na syntaxe
set number " habilita o numero de linhas
set relativenumber " calculo das distancias das linhas
set nocompatible " comporte-se como Vim em vez de Vi
set showcmd " mostra comandos que nao estejam completos"

set tabstop=2 shiftwidth=2 " configura 2 espacos no lugar do tab
set expandtab " configura 2 espacos no lugar do tab
set softtabstop=2 " respeita a indentacao

set encoding=utf-8 " visualiza a condificacao desejada
set fileenconding=utf-8 " configura codificacao desejada

set backspace=indent,eol,start

set hlsearch " destaque da busca
set incsearch " busca incremental
set ignorecase " desativa o case sensitive
set smartcase " correspondecias inteligenges

color darkblue " cor padrao para melhor visualizacao com o putty